---
- name: alerting rules file
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/rules/alert.rules"
    owner: prometheus
    group: prometheus
    mode: 0644
    validate: "{{ prometheus_rules_validator }}"
  when: prometheus_alertmanager_url != ""
  with_first_found:
    - files:
        - "rules/alert.rules.v{{ prometheus_version.split('.')[0] }}"
      paths:
        - "{{ prometheus_custom_alert_rules_path }}"
  notify:
    - reload prometheus

- name: configure prometheus
  template:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: yes
    owner: prometheus
    group: prometheus
    mode: 0644
    validate: "{{ prometheus_config_validator }}"
  with_first_found:
    - files:
        -  prometheus.yml.j2
      paths:
        - "{{ prometheus_custom_config_path }}"
  notify:
    - reload prometheus

- name: configure prometheus static targets
  template:
    src: "targets.yml.j2"
    dest: "{{ prometheus_config_dir }}/file_sd/targets.yml"
    force: yes
    owner: prometheus
    group: prometheus
    mode: 0644
  when: prometheus_targets != []
  notify:
    - reload prometheus
