---
- name: create prometheus system group
  group:
    name: prometheus
    system: yes
    state: present

- name: create prometheus system user
  user:
    name: prometheus
    system: yes
    shell: "/sbin/nologin"
    group: prometheus
    createhome: no

- name: create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: create prometheus configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: prometheus
    mode: 0750
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/conf.d"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"

- name: download prometheus binary to local folder
  become: no
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/prometheus"
  register: _download_binary
  until: _download_binary | success
  retries: 5
  delay: 2
  # run_once: true
  delegate_to: localhost
  check_mode: no

- name: remove prometheus binaries from old location
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/prometheus/prometheus
    - /opt/prometheus/promtool
    - /opt/prometheus

- name: propagate prometheus and promtool binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - prometheus
    - promtool
  check_mode: no
  notify:
    - restart prometheus

- name: create systemd service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart prometheus

- name: Install SELinux dependencies on RedHat OS family
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - policycoreutils-python
  register: _download_packages
  until: _download_packages | success
  retries: 5
  delay: 2
  when:
    - ansible_os_family == "RedHat"

- name: Allow prometheus to bind to port in SELinux on RedHat OS family
  seport:
    ports: "{{ prometheus_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_virtualization_type != "docker"

#- name: change pam nofile limits for prometheus
#  pam_limits:
#    domain: "prometheus"
#    limit_item: nofile
#    limit_type: "{{ item }}"
#    value: "1024"
#    use_max: yes
#  with_items:
#      - soft
#      - hard
#  notify:
#    - restart prometheus
