---
- debug:
    msg: "rules/alert.rules.v{{ prometheus_version.split('.')[0] }}"

- include: preflight.yml

- include: install.yml

- include: configure.yml

- name: ensure prometheus service is enabled
  service:
    name: prometheus
    enabled: yes
