---
- include: preflight.yml

- include: install.yml

- include: configure.yml

- name: ensure prometheus service is started and enabled
  systemd:
    name: prometheus
    state: started
    enabled: yes
