---
- include: preflight.yml

- include: install.yml
  become: yes

- include: configure.yml
  become: yes

- name: ensure prometheus service is started and enabled
  become: yes
  systemd:
    name: prometheus
    state: started
    enabled: yes
