---
- name: Run role
  hosts: all
  any_errors_fatal: true
  pre_tasks:
    - name: Set prometheus version from PROMETHEUS environment variable
      set_fact:
        prometheus_version: "{{ lookup('env', 'PROMETHEUS') | default('latest') }}"
    - name: Set prometheus version to latest when not set previously
      set_fact:
        prometheus_version: "latest"
      when: prometheus_version == ""
    - name: Show prometheus version used in tests
      debug:
        var: prometheus_version
  roles:
    - ansible-prometheus
